The dataset is from https://www.kaggle.com/datasets/subinium/emojiimage-dataset/data

In [1]:
import torch
import numpy as np

import EmojiModel
from utility.deviceUtility import get_best_available_device

import importlib
import random
import pandas as pd

importlib.reload(EmojiModel)

<module 'EmojiModel' from '/Users/Admin/Documents/MachineLearning/github/ovinger/4_recurrent_neural_networks/EmojiModel.py'>

$$c = \sqrt{a^2 + b^2}$$


In [2]:
device = get_best_available_device()


________________________

Device manager:
Running on device: mps
________________________


In [3]:


# df = pd.read_csv("../data/emoji/copy.csv")
# emoji_dict = dict(zip(df.iloc[:, 3], df.iloc[:, 1]))
# print(emoji_dict)


emoji_dict = {
    'dog': '🐶',
    'cat': '🐱',
    'fox': '🦊',
    'cookie': '🍪',
    'crown': '👑',
    'snake': '🐍',
    'cold': '🥶'
}



emoji_list = list(emoji_dict.values())

possible_chars = list(' ' + ''.join(set(''.join(emoji_dict.keys()))))
possible_chars

[' ',
 'g',
 'f',
 'e',
 't',
 'o',
 'k',
 'd',
 's',
 'i',
 'w',
 'r',
 'l',
 'x',
 'c',
 'n',
 'a']

In [4]:
char_encodings = np.eye(len(possible_chars))
char_encodings

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0

In [5]:

emoji_encoding = np.eye(len(emoji_dict))
emoji_encoding


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [6]:
largest_word_len = max([len(it) for it in emoji_dict.keys()])
largest_word_len

6

In [7]:

padded_keys = [key + " " * (largest_word_len - len(key)) for key in emoji_dict.keys()]

x_train = torch.tensor([
    [[char_encodings[possible_chars.index(a)]] for a in word] for word in padded_keys],
    dtype=torch.float, device=device)
print(x_train.shape)
x_train

torch.Size([7, 6, 1, 17])


/var/folders/9y/_5ktt35903qg07y2vr8r34_80000gn/T/ipykernel_6634/4293065903.py:3: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:281.)
  x_train = torch.tensor([


tensor([[[[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],

         [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0

In [8]:
y_train = torch.tensor(
    [
        [emoji_encoding[i] for _ in range(0, largest_word_len)] for i in
        range(0, len(emoji_encoding))
    ], dtype=torch.float, device=device)

print(y_train.shape)
y_train


torch.Size([7, 6, 7])


tensor([[[1., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.]],

        [[0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.]],

        [[0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.]],

        [[0., 0., 0., 0., 1., 0., 0.],
         [0., 0.,

In [9]:
model = EmojiModel.EmojiModel(len(char_encodings), len(emoji_encoding), dev=device)

model.train_model(x_train, y_train)

Starting training
epoch 0
Loss: 1.9694682359695435
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 10
epoch 11
epoch 12
epoch 13
epoch 14
epoch 15
epoch 16
epoch 17
epoch 18
epoch 19
epoch 20
epoch 21
epoch 22
epoch 23
epoch 24
epoch 25
epoch 26
epoch 27
epoch 28
epoch 29
epoch 30
epoch 31
epoch 32
epoch 33
epoch 34
epoch 35
epoch 36
epoch 37
epoch 38
epoch 39
epoch 40
epoch 41
epoch 42
epoch 43
epoch 44
epoch 45
epoch 46
epoch 47
epoch 48
epoch 49
epoch 50
epoch 51
epoch 52
epoch 53
epoch 54
epoch 55
epoch 56
epoch 57
epoch 58
epoch 59
epoch 60
epoch 61
epoch 62
epoch 63
epoch 64
epoch 65
epoch 66
epoch 67
epoch 68
epoch 69
epoch 70
epoch 71
epoch 72
epoch 73
epoch 74
epoch 75
epoch 76
epoch 77
epoch 78
epoch 79
epoch 80
epoch 81
epoch 82
epoch 83
epoch 84
epoch 85
epoch 86
epoch 87
epoch 88
epoch 89
epoch 90
epoch 91
epoch 92
epoch 93
epoch 94
epoch 95
epoch 96
epoch 97
epoch 98
epoch 99


In [10]:
def generate_emoji(string, showGradualGuess=False) -> str: 
    y = -1
    model.reset()
    for c in string:
        char_index = possible_chars.index(c if c in possible_chars else ' ')
        
        y = model.f(torch.tensor([[char_encodings[char_index]]], dtype=torch.float, device=device))
        
        print(f"Current guess is {emoji_list[y.argmax(1)]}") if showGradualGuess else None
    return emoji_list[y.argmax(1)]



In [11]:
print(emoji_dict.keys())
for e in emoji_dict.keys():
    print(generate_emoji(e, True))

dict_keys(['dog', 'cat', 'fox', 'cookie', 'crown', 'snake', 'cold'])
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
🐶
Current guess is 🥶
Current guess is 🐱
Current guess is 🐱
🐱
Current guess is 🦊
Current guess is 🦊
Current guess is 🦊
🦊
Current guess is 🥶
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
🍪
Current guess is 🥶
Current guess is 👑
Current guess is 👑
Current guess is 👑
Current guess is 👑
👑
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
🐍
Current guess is 🥶
Current guess is 🍪
Current guess is 🥶
Current guess is 🥶
🥶


In [12]:
scrambled = [''.join(random.sample(word, len(word))) for word in emoji_dict.keys()]
print(scrambled)
for e in scrambled:
    print(generate_emoji(e, True))

['dgo', 'cta', 'xfo', 'oockie', 'ornwc', 'nsake', 'clod']
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
🐶
Current guess is 🥶
Current guess is 🐱
Current guess is 🐱
🐱
Current guess is 🦊
Current guess is 🦊
Current guess is 🦊
🦊
Current guess is 🍪
Current guess is 🍪
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
🐶
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🐶
🐶
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
🐍
Current guess is 🥶
Current guess is 🥶
Current guess is 🥶
Current guess is 🥶
🥶


In [13]:
almost_same = ["doge", "cats", "fox", "coooki", "crovn", "snek"]
print(almost_same)
for e in almost_same:
    print(generate_emoji(e, True))

['doge', 'cats', 'fox', 'coooki', 'crovn', 'snek']
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
Current guess is 🐶
🐶
Current guess is 🥶
Current guess is 🐱
Current guess is 🐱
Current guess is 🐱
🐱
Current guess is 🦊
Current guess is 🦊
Current guess is 🦊
🦊
Current guess is 🥶
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
Current guess is 🍪
🍪
Current guess is 🥶
Current guess is 👑
Current guess is 👑
Current guess is 👑
Current guess is 👑
👑
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
🐍


In [14]:
print(generate_emoji("cat", True))
print(generate_emoji("smiley", True))

Current guess is 🥶
Current guess is 🐱
Current guess is 🐱
🐱
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
Current guess is 🐍
🐍
